In [1]:
#Imprort des librairies nécessaires
import pandas as pd
import numpy as np

In [2]:
#Preparation des jeux de données autobus:

#1)Nom de colonnes 
col_names_temp = ["Emissions","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018"]
col_names_ap_2010_temp = ["Emissions","2010","2011","2012","2013","2014","2015","2016","2017","2018"]
col_names_av_2010_temp = ["Emissions","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009"]
col_names_benz = ["Emissions","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018"]

#2)Lecture du fichier
emissions_poll_csv = 'emissions_polluantes.csv'
emissions_poll = pd.read_csv(emissions_poll_csv, sep=";",  quotechar='"', encoding="utf-8",header = None)

#3) Formatage Dataset
#Suppression des lignes vides
emissions_poll.dropna(axis=0,how='all',inplace=True)
#Suppression d'une ligne note inutile :
row_note = emissions_poll[emissions_poll[0] == "Note : somme des HAP tels que définis par la CEE-NU : benzo(a)pyrène, benzo(b)fluoranthène, benzo(k)fluoranthène et indeno(1,2,3-cd)pyrène"].index[0]
emissions_poll=emissions_poll.drop([row_note])
#Reset de l'index des lignes
emissions_poll.reset_index(drop=True,inplace=True)

#Cas du benzene : re-organisation des colonnes
emission_poll_benz=emissions_poll[460:]
cols_to_drop=[20, 21,22,23,24,25,26,27,28,29]
emission_poll_benz=emission_poll_benz.drop(cols_to_drop, axis=1)
emission_poll_benz.columns=col_names_benz
emission_poll_benz ["1990"] = "0"
emission_poll_benz ["1991"] = "0"
emission_poll_benz ["1992"] = "0"
emission_poll_benz ["1993"] = "0"
emission_poll_benz ["1994"] = "0"
emission_poll_benz ["1995"] = "0"
emission_poll_benz ["1996"] = "0"
emission_poll_benz ["1997"] = "0"
emission_poll_benz ["1998"] = "0"
emission_poll_benz ["1999"] = "0"
emission_poll_benz = emission_poll_benz[col_names_temp]

#Re-fusionage du benzene avec le reste du dataset
emissions_poll.columns =col_names_temp
emissions_poll=pd.concat([emissions_poll[:460],emission_poll_benz])

#4) Division du dataset en 2 (av et ap 2010)
emissions_poll_av_2010 = emissions_poll[col_names_av_2010_temp]
emissions_poll_ap_2010 = emissions_poll[col_names_ap_2010_temp]

In [3]:
emissions_poll.iloc[20 : 35]

,Emissions,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
20,Diesel,0,0,"0,040","0,11","0,17","0,22","0,27","0,32","0,36",...,"0,63","0,69","0,74","0,80","0,80","0,76","0,74","0,72","0,71","0,72"
21,Electriques,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,Ensemble des véhicules,1237,1244,1262,1215,1178,1117,1068,1032,1001,...,586,582,564,538,528,513,498,477,457,422
23,Diesel,493,520,551,560,576,584,582,595,601,...,533,539,529,510,502,491,479,460,442,408
24,Essence,742,722,709,654,600,532,485,434,396,...,52,42,34,28,24,22,18,16,15,13
25,Autres,"2,2","2,0","1,7","1,4","1,2","0,9","1,5","2,6","4,1",...,"0,9","0,9","1,1","1,0","1,0","0,9","0,9","0,8","0,8","0,9"
26,"Source : Citepa, avril 2020 - Format Secten",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,D2.2-b2 Émissions de COVNM du transport routie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en milliers de tonnes
29,NaN,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
30,Voitures particulières,723,706,704,659,592,546,489,444,401,...,66,58,47,41,36,32,31,28,27,25
31,Diesel,14,16,16,16,15,16,16,15,15,...,9,9,7,7,6,5,5,4,4,3
32,Essence,708,690,688,642,577,530,473,427,384,...,57,48,39,33,29,26,26,24,23,22
33,GPL,"0,73","0,73","0,61","0,55","0,46","0,41","0,71","1,36","2,23",...,"0,89","1,04","0,96","0,87","0,72","0,56","0,53","0,46","0,40","0,34"
34,GNV,0,0,0,"0,02","0,01",0,"0,01",0,0,...,"0,05","0,04","0,06","0,06","0,06","0,04","0,04","0,03","0,02","0,02"

In [4]:
emissions_poll[374:380]

,Emissions,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
374,Diesel,"2,0","2,2","2,5","2,6","2,8","3,0","3,1","3,3","3,4",...,"3,2","3,1","2,9","2,8","2,7","2,6","2,5","2,4","2,3","2,2"
375,Essence,"0,88","0,86","0,85","0,81","0,76","0,70","0,66","0,63","0,60",...,"0,30","0,29","0,27","0,25","0,25","0,25","0,25","0,26","0,27","0,28"
376,Autres,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
377,"Source : Citepa, avril 2020 - Format Secten",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,D2.2-b15 Émissions de PCDD-F du transport rout...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en grammes équivalents toxiques internationaux...

In [5]:
"D2.2-b" in str(emissions_poll_ap_2010["Emissions"][460])

False

In [6]:
#Recupère un dictionnaire des tableaux par emissions poulluante
def recup_tab_par_emissions(dataset):
    tab={}
    for row in range(len(dataset)):
        cell=dataset['Emissions'][row]
        if "D2.2-b" in str(cell):
            emission=cell.split()[3]
            #print(emission)
            deb=row+3
            #print(deb)
        if "Source" in str(cell):
            fin=row
            #print(fin)    
            tab[emission]=dataset[deb:fin]
            tab[emission].reset_index(drop=True,inplace=True)
            tab[emission]=tab[emission].replace({',': '.'}, regex=True)
            #Passage de tous les int en float
            temp=pd.DataFrame(tab[emission])
            temp_col_em = temp['Emissions']
            temp_autres_col=temp.loc[:, temp.columns != 'Emissions'].astype(float)
            temp= pd.concat([temp_col_em,temp_autres_col], axis=1)
            tab[emission]=temp
            continue
    return(tab)

In [7]:
#Recuperation des tableaux par type d'emissions
emissions_poll_ap_2010_em=recup_tab_par_emissions(emissions_poll_ap_2010)
emissions_poll_av_2010_em=recup_tab_par_emissions(emissions_poll_av_2010)

In [8]:
emissions_poll_av_2010_em["CO"].loc[:, emissions_poll_av_2010_em["CO"].columns != 'Emissions'].astype(float)

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,4528.00,4454.00,4302.000,4037.00,3406.00,3259.00,2937.00,2604.00,2369.00,2184.00,1786.00,1628.00,1400.00,1218.00,1097.00,883.00,723.00,647.00,544.00,440.00
1,56.00,62.00,66.000,70.00,70.00,75.00,78.00,77.00,75.00,73.00,63.00,62.00,58.00,56.00,51.00,47.00,44.00,43.00,41.00,41.00
2,4465.00,4385.00,4230.000,3961.00,3332.00,3179.00,2853.00,2515.00,2275.00,2087.00,1698.00,1543.00,1323.00,1147.00,1033.00,824.00,669.00,596.00,495.00,393.00
3,7.60,7.30,6.200,5.50,4.50,3.80,6.30,11.60,19.50,24.50,25.20,22.80,18.80,15.50,13.30,11.50,9.70,8.40,7.40,6.10
4,0.00,0.00,0.000,0.00,0.02,0.01,0.01,0.00,0.00,0.00,0.01,0.07,0.14,0.11,0.14,0.16,0.17,0.14,0.17,0.15
5,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,858.00,869.00,791.000,721.00,681.00,612.00,586.00,547.00,515.00,477.00,409.00,396.00,356.00,323.00,288.00,247.00,216.00,191.00,150.00,143.00
7,68.00,77.00,83.000,90.00,91.00,91.00,87.00,83.00,79.00,76.00,69.00,68.00,66.00,65.00,62.00,59.00,55.00,53.00,50.00,50.00
8,790.00,793.00,708.000,631.00,590.00,521.00,499.00,464.00,436.00,401.00,340.00,328.00,289.00,258.00,226.00,188.00,160.00,138.00,100.00,93.00
9,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,94.00,97.00,102.000,101.00,102.00,99.00,96.00,99.00,96.00,94.00,92.00,89.00,87.00,83.00,88.00,87.00,89.00,86.00,71.00,60.00
11,94.00,97.00,102.000,101.00,101.00,98.00,96.00,98.00,96.00,93.00,92.00,88.00,86.00,83.00,88.00,87.00,89.00,86.00,71.00,60.00
12,0.28,0.27,0.270,0.25,0.24,0.23,0.22,0.23,0.23,0.23,0.23,0.21,0.23,0.20,0.22,0.22,0.20,0.15,0.13,0.11
13,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.08,0.08,0.11,0.11,0.11,0.13,0.14,0.15,0.14
14,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,108.00,108.00,111.000,138.00,121.00,105.00,105.00,130.00,163.00,169.00,181.00,188.00,196.00,184.00,182.00,167.00,146.00,133.00,120.00,112.00
16,108.00,108.00,111.000,138.00,121.00,105.00,105.00,130.00,163.00,169.00,180.00,188.00,195.00,183.00,181.00,167.00,145.00,132.00,119.00,111.00
17,0.00,0.00,0.046,0.12,0.19,0.25,0.31,0.37,0.41,0.45,0.47,0.49,0.50,0.50,0.50,0.51,0.54,0.59,0.65,0.71
18,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
19,5588.00,5529.00,5307.000,4997.00,4310.00,4075.00,3725.00,3379.00,3144.00,2924.00,2468.00,2301.00,2038.00,1809.00,1655.00,1385.00,1174.00,1057.00,885.00,755.00
20,218.00,235.00,252.000,261.00,263.00,265.00,261.00,258.00,250.00,243.00,224.00,219.00,211.00,204.00,201.00,194.00,189.00,181.00,163.00,151.00
21,5363.00,5286.00,5049.000,4731.00,4042.00,3806.00,3458.00,3109.00,2874.00,2657.00,2219.00,2059.00,1808.00,1589.00,1441.00,1179.00,975.00,867.00,714.00,597.00
22,7.60,7.30,6.200,5.50,4.60,3.80,6.30,11.60,19.50,24.50,25.20,22.90,19.00,15.70,13.60,11.70,10.10,8.70,7.80,6.40

In [9]:
temp=pd.DataFrame(emissions_poll_av_2010_em["CO"])
temp_col_em = temp['Emissions']
temp_autres_col=temp.loc[:, temp.columns != 'Emissions'].astype(float)
temp= pd.concat([temp_col_em,temp_autres_col], axis=1)
temp

,Emissions,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,Voitures particulières,4528.00,4454.00,4302.000,4037.00,3406.00,3259.00,2937.00,2604.00,2369.00,...,1786.00,1628.00,1400.00,1218.00,1097.00,883.00,723.00,647.00,544.00,440.00
1,Diesel,56.00,62.00,66.000,70.00,70.00,75.00,78.00,77.00,75.00,...,63.00,62.00,58.00,56.00,51.00,47.00,44.00,43.00,41.00,41.00
2,Essence,4465.00,4385.00,4230.000,3961.00,3332.00,3179.00,2853.00,2515.00,2275.00,...,1698.00,1543.00,1323.00,1147.00,1033.00,824.00,669.00,596.00,495.00,393.00
3,GPL,7.60,7.30,6.200,5.50,4.50,3.80,6.30,11.60,19.50,...,25.20,22.80,18.80,15.50,13.30,11.50,9.70,8.40,7.40,6.10
4,GNV,0.00,0.00,0.000,0.00,0.02,0.01,0.01,0.00,0.00,...,0.01,0.07,0.14,0.11,0.14,0.16,0.17,0.14,0.17,0.15
5,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,Véhicules utilitaires,858.00,869.00,791.000,721.00,681.00,612.00,586.00,547.00,515.00,...,409.00,396.00,356.00,323.00,288.00,247.00,216.00,191.00,150.00,143.00
7,Diesel,68.00,77.00,83.000,90.00,91.00,91.00,87.00,83.00,79.00,...,69.00,68.00,66.00,65.00,62.00,59.00,55.00,53.00,50.00,50.00
8,Essence,790.00,793.00,708.000,631.00,590.00,521.00,499.00,464.00,436.00,...,340.00,328.00,289.00,258.00,226.00,188.00,160.00,138.00,100.00,93.00
9,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,Poids lourds,94.00,97.00,102.000,101.00,102.00,99.00,96.00,99.00,96.00,...,92.00,89.00,87.00,83.00,88.00,87.00,89.00,86.00,71.00,60.00
11,Diesel,94.00,97.00,102.000,101.00,101.00,98.00,96.00,98.00,96.00,...,92.00,88.00,86.00,83.00,88.00,87.00,89.00,86.00,71.00,60.00
12,Essence,0.28,0.27,0.270,0.25,0.24,0.23,0.22,0.23,0.23,...,0.23,0.21,0.23,0.20,0.22,0.22,0.20,0.15,0.13,0.11
13,GNV,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.08,0.08,0.11,0.11,0.11,0.13,0.14,0.15,0.14
14,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,Deux roues,108.00,108.00,111.000,138.00,121.00,105.00,105.00,130.00,163.00,...,181.00,188.00,196.00,184.00,182.00,167.00,146.00,133.00,120.00,112.00
16,Essence,108.00,108.00,111.000,138.00,121.00,105.00,105.00,130.00,163.00,...,180.00,188.00,195.00,183.00,181.00,167.00,145.00,132.00,119.00,111.00
17,Diesel,0.00,0.00,0.046,0.12,0.19,0.25,0.31,0.37,0.41,...,0.47,0.49,0.50,0.50,0.50,0.51,0.54,0.59,0.65,0.71
18,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
19,Ensemble des véhicules,5588.00,5529.00,5307.000,4997.00,4310.00,4075.00,3725.00,3379.00,3144.00,...,2468.00,2301.00,2038.00,1809.00,1655.00,1385.00,1174.00,1057.00,885.00,755.00
20,Diesel,218.00,235.00,252.000,261.00,263.00,265.00,261.00,258.00,250.00,...,224.00,219.00,211.00,204.00,201.00,194.00,189.00,181.00,163.00,151.00
21,Essence,5363.00,5286.00,5049.000,4731.00,4042.00,3806.00,3458.00,3109.00,2874.00,...,2219.00,2059.00,1808.00,1589.00,1441.00,1179.00,975.00,867.00,714.00,597.00
22,Autres,7.60,7.30,6.200,5.50,4.60,3.80,6.30,11.60,19.50,...,25.20,22.90,19.00,15.70,13.60,11.70,10.10,8.70,7.80,6.40

In [10]:
emissions_poll_av_2010_em.keys()

dict_keys(['NOx', 'COVNM', 'CO', 'PM10', 'PM2,5', 'PM1', 'BC', 'du', 'Cd', 'Cr', 'Cu', 'Pb', 'Zn', 'HAP', 'PCDD-F', 'SO2', 'Ni', 'benzène'])

In [11]:
emissions_poll_av_2010_em["CO"]

,Emissions,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009
0,Voitures particulières,4528.00,4454.00,4302.000,4037.00,3406.00,3259.00,2937.00,2604.00,2369.00,...,1786.00,1628.00,1400.00,1218.00,1097.00,883.00,723.00,647.00,544.00,440.00
1,Diesel,56.00,62.00,66.000,70.00,70.00,75.00,78.00,77.00,75.00,...,63.00,62.00,58.00,56.00,51.00,47.00,44.00,43.00,41.00,41.00
2,Essence,4465.00,4385.00,4230.000,3961.00,3332.00,3179.00,2853.00,2515.00,2275.00,...,1698.00,1543.00,1323.00,1147.00,1033.00,824.00,669.00,596.00,495.00,393.00
3,GPL,7.60,7.30,6.200,5.50,4.50,3.80,6.30,11.60,19.50,...,25.20,22.80,18.80,15.50,13.30,11.50,9.70,8.40,7.40,6.10
4,GNV,0.00,0.00,0.000,0.00,0.02,0.01,0.01,0.00,0.00,...,0.01,0.07,0.14,0.11,0.14,0.16,0.17,0.14,0.17,0.15
5,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,Véhicules utilitaires,858.00,869.00,791.000,721.00,681.00,612.00,586.00,547.00,515.00,...,409.00,396.00,356.00,323.00,288.00,247.00,216.00,191.00,150.00,143.00
7,Diesel,68.00,77.00,83.000,90.00,91.00,91.00,87.00,83.00,79.00,...,69.00,68.00,66.00,65.00,62.00,59.00,55.00,53.00,50.00,50.00
8,Essence,790.00,793.00,708.000,631.00,590.00,521.00,499.00,464.00,436.00,...,340.00,328.00,289.00,258.00,226.00,188.00,160.00,138.00,100.00,93.00
9,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,Poids lourds,94.00,97.00,102.000,101.00,102.00,99.00,96.00,99.00,96.00,...,92.00,89.00,87.00,83.00,88.00,87.00,89.00,86.00,71.00,60.00
11,Diesel,94.00,97.00,102.000,101.00,101.00,98.00,96.00,98.00,96.00,...,92.00,88.00,86.00,83.00,88.00,87.00,89.00,86.00,71.00,60.00
12,Essence,0.28,0.27,0.270,0.25,0.24,0.23,0.22,0.23,0.23,...,0.23,0.21,0.23,0.20,0.22,0.22,0.20,0.15,0.13,0.11
13,GNV,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.08,0.08,0.11,0.11,0.11,0.13,0.14,0.15,0.14
14,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
15,Deux roues,108.00,108.00,111.000,138.00,121.00,105.00,105.00,130.00,163.00,...,181.00,188.00,196.00,184.00,182.00,167.00,146.00,133.00,120.00,112.00
16,Essence,108.00,108.00,111.000,138.00,121.00,105.00,105.00,130.00,163.00,...,180.00,188.00,195.00,183.00,181.00,167.00,145.00,132.00,119.00,111.00
17,Diesel,0.00,0.00,0.046,0.12,0.19,0.25,0.31,0.37,0.41,...,0.47,0.49,0.50,0.50,0.50,0.51,0.54,0.59,0.65,0.71
18,Electriques,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
19,Ensemble des véhicules,5588.00,5529.00,5307.000,4997.00,4310.00,4075.00,3725.00,3379.00,3144.00,...,2468.00,2301.00,2038.00,1809.00,1655.00,1385.00,1174.00,1057.00,885.00,755.00
20,Diesel,218.00,235.00,252.000,261.00,263.00,265.00,261.00,258.00,250.00,...,224.00,219.00,211.00,204.00,201.00,194.00,189.00,181.00,163.00,151.00
21,Essence,5363.00,5286.00,5049.000,4731.00,4042.00,3806.00,3458.00,3109.00,2874.00,...,2219.00,2059.00,1808.00,1589.00,1441.00,1179.00,975.00,867.00,714.00,597.00
22,Autres,7.60,7.30,6.200,5.50,4.60,3.80,6.30,11.60,19.50,...,25.20,22.90,19.00,15.70,13.60,11.70,10.10,8.70,7.80,6.40

In [12]:
# Pour un tableau émission donné, récupère un dictionnaire des sous tableaux par catégorie de véhicule

def recup_sub_tab_par_cat_vehicule(tab_em,tab_colnames,emission):
    cat_vehicule= ["Voitures particulières","Véhicules utilitaires","Poids lourds","Deux roues","Ensemble des véhicules"]
    
    ###Etape 1 : recuperation des ss-tableaux de catégorie de véhicule dans un dico
   
    #Récuperation des lignes de séparation entre chaque ss-tableaux 
    sep=[l for l in range(len(tab_em)) if str(tab_em['Emissions'][l]) in cat_vehicule]
    sep.append(len(tab_em))
    #return(sep)

    #Récuperation des ss-tableaux
    sub_tab=dict()
    for s in range(len(sep)-1) :
        sub_tab[cat_vehicule[s]]=tab_em[sep[s]+1:sep[s+1]] 
    #return (sub_tab)
    
    #Etape 2 : pivot de chaque ss-tableau
    sub_tab_transfo=dict()
    
    for cat in sub_tab:
        sub_tab_transfo[cat]=sub_tab[cat].transpose()
        sub_tab_transfo[cat].reset_index(inplace=True)
        sub_tab_transfo[cat]["index"][0]="Année"
        sub_tab_transfo[cat].columns = sub_tab_transfo[cat].iloc[0]
        sub_tab_transfo[cat]=sub_tab_transfo[cat][1:]
        sub_tab_transfo[cat]["Polluant"]=emission
    return (sub_tab_transfo)

In [13]:
emissions_poll_ap_2010_em_veh={}
for em in emissions_poll_ap_2010_em:
    emissions_poll_ap_2010_em_veh[em]=recup_sub_tab_par_cat_vehicule(emissions_poll_ap_2010_em[em],col_names_ap_2010_temp,em)

emissions_poll_av_2010_em_veh={}
for em in emissions_poll_av_2010_em:
    emissions_poll_av_2010_em_veh[em]=recup_sub_tab_par_cat_vehicule(emissions_poll_av_2010_em[em],col_names_av_2010_temp,em)

In [14]:
emissions_poll_av_2010_em_veh["benzène"]

{'Voitures particulières': 0  Année Diesel Essence GPL GNV Electriques Polluant
 1   1990      0       0   0   0           0  benzène
 2   1991      0       0   0   0           0  benzène
 3   1992      0       0   0   0           0  benzène
 4   1993      0       0   0   0           0  benzène
 5   1994      0       0   0   0           0  benzène
 6   1995      0       0   0   0           0  benzène
 7   1996      0       0   0   0           0  benzène
 8   1997      0       0   0   0           0  benzène
 9   1998      0       0   0   0           0  benzène
 10  1999      0       0   0   0           0  benzène
 11  2000    618   10223   0   0           0  benzène
 12  2001    632    9226   0   0           0  benzène
 13  2002    595    7875   0   0           0  benzène
 14  2003    589    6759   0   0           0  benzène
 15  2004    552    5814   0   0           0  benzène
 16  2005    522    4646   0   0           0  benzène
 17  2006    480    3680   0   0           0  benzène
 18  2007    461    3062   0   0           0  benzène
 19  2008    439    2426   0   0           0  benzène
 20  2009    432    1981   0   0           0  benzène,
 'Véhicules utilitaires': 0  Année Diesel Essence Electriques Polluant
 1   1990      0       0           0  benzène
 2   1991      0       0           0  benzène
 3   1992      0       0           0  benzène
 4   1993      0       0           0  benzène
 5   1994      0       0           0  benzène
 6   1995      0       0           0  benzène
 7   1996      0       0           0  benzène
 8   1997      0       0           0  benzène
 9   1998      0       0           0  benzène
 10  1999      0       0           0  benzène
 11  2000    593    1306           0  benzène
 12  2001    628    1253           0  benzène
 13  2002    626    1105           0  benzène
 14  2003    621     984           0  benzène
 15  2004    609     848           0  benzène
 16  2005    601     696           0  benzène
 17  2006    572     572           0  benzène
 18  2007    538     450           0  benzène
 19  2008    487     307           0  benzène
 20  2009    455     259           0  benzène,
 'Poids lourds': 0  Année Diesel Essence GNV Electriques Polluant
 1   1990      0       0   0           0  benzène
 2   1991      0       0   0           0  benzène
 3   1992      0       0   0           0  benzène
 4   1993      0       0   0           0  benzène
 5   1994      0       0   0           0  benzène
 6   1995      0       0   0           0  benzène
 7   1996      0       0   0           0  benzène
 8   1997      0       0   0           0  benzène
 9   1998      0       0   0           0  benzène
 10  1999      0       0   0           0  benzène
 11  2000   1251     9.8   0           0  benzène
 12  2001   1121     9.1   0           0  benzène
 13  2002   1057     9.8   0           0  benzène
 14  2003    956     8.8   0           0  benzène
 15  2004    935     9.4   0           0  benzène
 16  2005    933     9.3   0           0  benzène
 17  2006    900     8.7   0           0  benzène
 18  2007    799     6.4   0           0  benzène
 19  2008    618     5.5   0           0  benzène
 20  2009    480     4.9   0           0  benzène,
 'Deux roues': 0  Année Essence Diesel Electriques Polluant
 1   1990       0      0           0  benzène
 2   1991       0      0           0  benzène
 3   1992       0      0           0  benzène
 4   1993       0      0           0  benzène
 5   1994       0      0           0  benzène
 6   1995       0      0           0  benzène
 7   1996       0      0           0  benzène
 8   1997       0      0           0  benzène
 9   1998       0      0           0  benzène
 10  1999       0      0           0  benzène
 11  2000    1138      0           0  benzène
 12  2001    1150      0           0  benzène
 13  2002    1160      0           0  benzène
 14  2003    1081      0           0  benzène
 15  2004    1105      0           0  benzène
 16  2005    1067      0           0  benzène
 17  2006     986      0           0  benzène
 18  2007     924      0           0  benzène
 19  2008     895      0           0  benzène
 20  2009     880      0           0  benzène,
 'Ensemble des véhicules': 0  Année Diesel Essence Autres Polluant
 1   1990      0       0      0  benzène
 2   1991      0       0      0  benzène
 3   1992      0       0      0  benzène
 4   1993      0       0      0  benzène
 5   1994      0       0      0  benzène
 6   1995      0       0      0  benzène
 7   1996      0       0      0  benzène
 8   1997      0       0      0  benzène
 9   1998      0       0      0  benzène
 10  1999      0       0      0  benzène
 11  2000   2462   12676      0  benzène
 12  2001   2381   11639      0  benzène
 13  2002   2278   10150      0  benzène
 14  2003   2166    8833      0  benzène
 15  2004   2096    7776      0  benzène
 16  2005   2057    6418      0  benzène
 17  2006   1952    5247      0  benzène
 18  2007   1798    4442      0  benzène
 19  2008   1545    3633      0  benzène
 20  2009   1367    3125      0  benzène}

In [15]:
emissions_poll_ap_2010_em_veh["Cu"]["Voitures particulières"]

0 Année Diesel Essence   GPL GNV Electriques Polluant
1  2010     52      21   0.4   0           0       Cu
2  2011     55      20  0.48   0           0       Cu
3  2012     56      18  0.44   0        0.02       Cu
4  2013     56      18   0.4   0        0.03       Cu
5  2014     56      18  0.36   0        0.06       Cu
6  2015     57      18  0.33   0        0.09       Cu
7  2016     58      19   0.3   0        0.14       Cu
8  2017     56      20  0.27   0        0.21       Cu
9  2018     54      21  0.25   0        0.29       Cu

In [16]:
#Concatene toutes les émissions par catégorie de véhicule 
def concat_tab_em_veh (tab_em_veh):
    cat_vehicule= ["Voitures particulières","Véhicules utilitaires","Poids lourds","Deux roues","Ensemble des véhicules"]
    tab_concat=dict()
    for cat in cat_vehicule:
        tab_to_concat=list()
        for em in tab_em_veh:
            tab_to_concat.append(tab_em_veh[em][cat])
        tab_concat[cat]=pd.concat(tab_to_concat)
        tab_concat[cat].reset_index(drop=True, inplace=True)
    return(tab_concat)

In [17]:
emissions_poll_ap_2010_merged= concat_tab_em_veh(emissions_poll_ap_2010_em_veh)
emissions_poll_av_2010_merged= concat_tab_em_veh(emissions_poll_av_2010_em_veh)

In [18]:
emissions_poll_ap_2010_merged.keys()

dict_keys(['Voitures particulières', 'Véhicules utilitaires', 'Poids lourds', 'Deux roues', 'Ensemble des véhicules'])

In [19]:
emissions_poll_ap_2010_merged['Voitures particulières']

0   Année Diesel Essence  GPL    GNV Electriques Polluant
0    2010    204      33  0.7  0.016           0      NOx
1    2011    202      27  0.7  0.023           0      NOx
2    2012    207      21  0.5  0.022           0      NOx
3    2013    207      18  0.4  0.022           0      NOx
4    2014    210      16  0.4  0.014           0      NOx
..    ...    ...     ...  ...    ...         ...      ...
157  2014    247     814    0      0           0  benzène
158  2015    232     810    0      0           0  benzène
159  2016    200     752    0      0           0  benzène
160  2017    184     713    0      0           0  benzène
161  2018    157     659    0      0           0  benzène

[162 rows x 7 columns]

In [20]:
cat_vehicule= ["Voitures particulières","Véhicules utilitaires","Poids lourds","Deux roues","Ensemble des véhicules"]
emissions_poll_av_2010_merged_v2=dict()
emissions_poll_ap_2010_merged_v2=dict()
for cat in cat_vehicule:
    emissions_poll_av_2010_merged_v2[cat]=pd.melt(emissions_poll_av_2010_merged[cat] , id_vars=['Année', 'Polluant'], value_vars= emissions_poll_av_2010_merged[cat].columns[1:-1], value_name="Emissions", var_name="Fuel")
    emissions_poll_ap_2010_merged_v2[cat]=pd.melt(emissions_poll_ap_2010_merged[cat] , id_vars=['Année', 'Polluant'], value_vars= emissions_poll_ap_2010_merged[cat].columns[1:-1], value_name="Emissions", var_name="Fuel")

In [21]:
emissions_poll_av_2010_merged_v2["Poids lourds"]

     Année Polluant         Fuel Emissions
0     1990      NOx       Diesel       347
1     1991      NOx       Diesel       359
2     1992      NOx       Diesel       374
3     1993      NOx       Diesel       369
4     1994      NOx       Diesel       375
...    ...      ...          ...       ...
1435  2005  benzène  Electriques         0
1436  2006  benzène  Electriques         0
1437  2007  benzène  Electriques         0
1438  2008  benzène  Electriques         0
1439  2009  benzène  Electriques         0

[1440 rows x 4 columns]

In [22]:
pd.melt(emissions_poll_av_2010_merged["Poids lourds"] , id_vars=['Année', 'Polluant'], value_vars= emissions_poll_av_2010_merged["Poids lourds"].columns[1:-1], value_name="Emissions", var_name="Fuel")

     Année Polluant         Fuel Emissions
0     1990      NOx       Diesel       347
1     1991      NOx       Diesel       359
2     1992      NOx       Diesel       374
3     1993      NOx       Diesel       369
4     1994      NOx       Diesel       375
...    ...      ...          ...       ...
1435  2005  benzène  Electriques         0
1436  2006  benzène  Electriques         0
1437  2007  benzène  Electriques         0
1438  2008  benzène  Electriques         0
1439  2009  benzène  Electriques         0

[1440 rows x 4 columns]

In [23]:
emissions_poll_ap_2010_merged["Poids lourds"]

0   Année Diesel Essence   GNV Electriques Polluant
0    2010    235    0.11  0.22           0      NOx
1    2011  226.9     0.1  0.39           0      NOx
2    2012    201    0.08  0.43           0      NOx
3    2013    189    0.07   0.5           0      NOx
4    2014    168    0.03  0.57           0      NOx
..    ...    ...     ...   ...         ...      ...
157  2014    247     1.4     0           0  benzène
158  2015    214     1.2     0           0  benzène
159  2016    181    0.41     0           0  benzène
160  2017    160   0.055     0           0  benzène
161  2018    135   0.087     0           0  benzène

[162 rows x 6 columns]

In [24]:
def ecriture_fichiers_transfo (tab_merged,years) :
    cat_vehicule= ["Voitures particulières","Véhicules utilitaires","Poids lourds","Deux roues","Ensemble des véhicules"]
    for cat in cat_vehicule:
        cat_str=cat.lower()
        cat_str=cat_str.replace("é","e")
        cat_str=cat_str.replace("è","e")
        cat_str="_".join(cat_str.split())
        name_csv= cat_str+years+".csv"
        tab_merged[cat].to_csv(name_csv,sep=';', index = False)

In [25]:
ecriture_fichiers_transfo(emissions_poll_ap_2010_merged,"_ap_2010")
ecriture_fichiers_transfo(emissions_poll_av_2010_merged,"_av_2010")

ecriture_fichiers_transfo(emissions_poll_ap_2010_merged_v2,"_ap_2010_v2")
ecriture_fichiers_transfo(emissions_poll_av_2010_merged_v2,"_av_2010_v2")